### ISSUE TITLE
Launch error on Android

### ISSUE THREAD

**Issue by caspahouzer** [viezel/NappJockey#12]
Hey @viezel,

I unfortunately got an error on starting my Android app with SDK 6.0.0.GA

This is the stack:

```log
[ERROR] :  dalvikvm: dlopen("/data/app-lib/com.hood.media-1/libdk.napp.jockey.so") failed: Cannot load library: load_library(linker.cpp:750): library "/system/lib/libhoudini.so" not found
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa6147908)
[ERROR] :  TiApplication: (main) [307,346] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: Cannot load library: load_library(linker.cpp:750): library "/system/lib/libhoudini.so" not found; Titanium 6.0.0,2016/12/12 04:19,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: Cannot load library: load_library(linker.cpp:750): library "/system/lib/libhoudini.so" not found
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:535)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] :  TiApplication: 	at com.hood.media.HoodApplication.onCreate(HoodApplication.java:55)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$1300(ActivityThread.java:141)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:137)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5041)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:511)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)
[ERROR] :  I/dalvikvm-heap(  396): Grow heap (frag case) to 6.058MB for 281892-byte allocation
```

Any tipps what I can do? I really need your module. I build my app for iOS and it's completed. Now I want to make my refactoring for Android.

**Comment by caspahouzer** [comment]
Ok, I found a solution for it here: [http://www.rajatswarup.com/blog/2015/02/24/genymotion-and-libhoudini-so-error/](http://www.rajatswarup.com/blog/2015/02/24/genymotion-and-libhoudini-so-error/)

But after that, another error comes along

    [ERROR] :  dalvikvm: dlopen("/data/app-lib/com.hood.media-1/libdk.napp.jockey.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1640): could not load library "libstlport_shared.so" needed by "libdk.napp.jockey.so"; caused by load_library(linker.cpp:750): library "libstlport_shared.so" not found

I'll take a further look

**Comment by caspahouzer** [comment]
The solution seems this: [http://stackoverflow.com/questions/23846566/failed-to-build-project-libstlport-shared-so-not-found](http://stackoverflow.com/questions/23846566/failed-to-build-project-libstlport-shared-so-not-found)

```
static {
    System.loadLibrary("stlport_shared");
}
```

But I'm a straight Titanium and lower iOS developer. I really don't know what to do with the solution. Maybe you can help?
